project:
  type: website
  output-dir: docs

website:
  title: "Albart Coster"
  description: "Albart Coster, dierwetenschapper, combineert wetenschap en praktische ervaring in dagelijks advieswerk."
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      ## - href: posts
      ##  text: Aantekeningen
      - href: presentaties.qmd
        text: Presentaties
      
  page-footer:
    left: " Albart Coster, 2025–."
  ## twitter-card: true
  ## open-graph: true
  ## google-analytics: "395640625"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
   
babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: nl
    text: "Nederlands"
  - name: en
    text: "Englisch"
  mainlanguage: 'nl'
  languages: ['en']
title-en: Albart Coster
description-en: Albart Coster's website
author-en: Albart Coster
lang: nl
