project:
  type: website
  output-dir: docs
resources:
  - CNAME

website:
  title: "Albart Coster"
  description: "Albart Coster, dierwetenschapper, combineert wetenschap en praktische ervaring in dagelijks advieswerk."
  navbar:
    left:
      - href: index.qmd
        text: Home
      ## - href: posts
      ##  text: Aantekeningen
      - href: presentaties.qmd
        text: Presentaties
      
  page-footer:
    left: " Albart Coster, 2025–."
  ## twitter-card: true
  ## open-graph: true
  ## google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
        



